-- Memory semantic search upgrade (AI/LLM memory enhancement).
--
-- Turns the memory table from a substring-searchable log into a retrieval layer:
--   * pgvector embeddings (gte-small, 384 dims, generated by the jmm-mcp edge function)
--   * full-text search column for keyword recall
--   * memory_recall(): hybrid vector + keyword retrieval (blended scoring)
--     weighted by importance, recency, and how often a memory gets referenced
--   * memory_find_similar(): near-duplicate check used at write time
--   * memory_mark_referenced(): reinforcement — retrieval bumps last_referenced
--     and reference_count, which feed back into ranking
--   * lifecycle columns: importance (1-5), status (active/archived), status_reason
--
-- Idempotent: safe to re-run. Apply with `supabase db push` or paste into the
-- Supabase SQL editor.

set search_path = public, extensions;

-- pgvector; guarded so a pre-existing install (any schema) is left alone.
do $$
begin
  if not exists (select 1 from pg_extension where extname = 'vector') then
    create extension vector with schema extensions;
  end if;
end
$$;

alter table memory add column if not exists embedding vector(384);
alter table memory add column if not exists embedding_model text;
alter table memory add column if not exists importance smallint not null default 3;
alter table memory add column if not exists status text not null default 'active';
alter table memory add column if not exists status_reason text;
alter table memory add column if not exists reference_count integer not null default 0;
alter table memory add column if not exists last_referenced timestamptz;
alter table memory add column if not exists content_tsv tsvector
  generated always as (to_tsvector('english', coalesce(content, ''))) stored;

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'memory_importance_range') then
    alter table memory add constraint memory_importance_range check (importance between 1 and 5);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'memory_status_valid') then
    alter table memory add constraint memory_status_valid check (status in ('active', 'archived'));
  end if;
end
$$;

create index if not exists memory_embedding_hnsw on memory using hnsw (embedding vector_cosine_ops);
create index if not exists memory_content_tsv_gin on memory using gin (content_tsv);
create index if not exists memory_tags_gin on memory using gin (tags);
create index if not exists memory_layer_status_idx on memory (layer, status);

comment on column memory.embedding is 'gte-small (384-dim) embedding of content; null until embedded (see backfill_memory_embeddings)';
comment on column memory.embedding_model is 'Model that produced embedding; null when embedding is null';
comment on column memory.importance is '1 (trivial) to 5 (load-bearing); multiplies recall score';
comment on column memory.status is 'active | archived. Archived memories are excluded from recall and default search.';
comment on column memory.status_reason is 'Why the memory was archived, e.g. superseded-by note';
comment on column memory.reference_count is 'Times returned by recall; reinforcement signal in ranking';

-- Hybrid recall. Two candidate lists — vector cosine similarity and full-text
-- keyword rank (OR of the query's lexemes, so partial term matches count) —
-- blended on a common 0..1 relevance scale, then nudged by boosts. Relevance
-- dominates; boosts only settle ties (rank-fusion approaches let a recency
-- boost outvote a large similarity gap, so absolute signals are used instead).
-- Either input may be null (vector-only / keyword-only recall).
--
-- Signal rescaling (tunable constants live in the fused CTE):
--   vscore: cosine similarity mapped so the gte-small "unrelated" baseline
--           (~0.55) is 0 and ~0.95 is 1
--   kscore: ts_rank_cd x / (x + 0.1), mapping typical short-note ranks to 0..1
--   relevance = strongest signal + 0.15 * the other (cross-signal bonus)
-- Boosts: importance 0.8-1.2, recency 0.8-1.0 (180-day decay anchored on the
-- most recent of created_at / last_referenced, so referenced memories stay
-- fresh), usage 1.0-~1.16 (log of reference_count, capped).
-- Strong matches typically score >= ~0.4.
create or replace function public.memory_recall(
  p_query text default null,
  p_embedding vector(384) default null,
  p_layer text default null,
  p_tag text default null,
  p_limit integer default 8,
  p_min_score double precision default 0
)
returns table (
  id uuid,
  layer text,
  content text,
  tags text[],
  source_context text,
  importance smallint,
  created_at timestamptz,
  last_referenced timestamptz,
  reference_count integer,
  similarity double precision,
  keyword_rank real,
  match_reason text,
  score double precision
)
language sql
stable
set search_path = public, extensions
as $$
  with params as (
    -- OR-of-lexemes tsquery: 'pricing approach for Deejo' -> 'price' | 'approach' | 'deejo'.
    -- Multi-term matches still rank higher via ts_rank_cd; stopword-only input yields null.
    select (
      select to_tsquery('english', string_agg('''' || replace(t.lexeme, '''', '''''') || '''', ' | '))
      from unnest(to_tsvector('english', coalesce(p_query, ''))) as t
    ) as q
  ),
  vec as (
    select m.id,
           (1 - (m.embedding <=> p_embedding))::double precision as sim
    from memory m
    where p_embedding is not null
      and m.embedding is not null
      and m.status = 'active'
      and (p_layer is null or m.layer = p_layer)
      and (p_tag is null or p_tag = any(m.tags))
    order by m.embedding <=> p_embedding
    limit 40
  ),
  lex as (
    select m.id,
           ts_rank_cd(m.content_tsv, params.q)::double precision as krank
    from memory m, params
    where params.q is not null
      and m.content_tsv @@ params.q
      and m.status = 'active'
      and (p_layer is null or m.layer = p_layer)
      and (p_tag is null or p_tag = any(m.tags))
    order by ts_rank_cd(m.content_tsv, params.q) desc
    limit 40
  ),
  fused as (
    select coalesce(v.id, l.id) as id,
           v.sim,
           l.krank,
           greatest(least((coalesce(v.sim, 0) - 0.55) / 0.40, 1), 0) as vscore,
           coalesce(l.krank, 0) / (coalesce(l.krank, 0) + 0.1) as kscore,
           case
             when v.id is not null and l.id is not null then 'semantic+keyword'
             when v.id is not null then 'semantic'
             else 'keyword'
           end as match_reason
    from vec v
    full outer join lex l on v.id = l.id
  ),
  scored as (
    select m.id, m.layer, m.content, m.tags, m.source_context,
           m.importance, m.created_at, m.last_referenced, m.reference_count,
           f.sim as similarity,
           f.krank::real as keyword_rank,
           f.match_reason,
           ((greatest(f.vscore, f.kscore) + 0.15 * least(f.vscore, f.kscore))
             * (0.7 + 0.1 * m.importance)
             * (0.8 + 0.2 * exp(-(extract(epoch from (now() - greatest(m.created_at, coalesce(m.last_referenced, m.created_at)))) / 86400.0) / 180.0))
             * (1 + 0.04 * ln(1 + least(m.reference_count, 50)))
           )::double precision as score
    from fused f
    join memory m on m.id = f.id
  )
  select *
  from scored
  where score >= p_min_score
  order by score desc
  limit greatest(p_limit, 1)
$$;

-- Nearest active memories by embedding; used for near-duplicate detection at
-- write time (and available as a pure-vector recall path).
create or replace function public.memory_find_similar(
  p_embedding vector(384),
  p_layer text default null,
  p_limit integer default 3,
  p_exclude uuid default null
)
returns table (
  id uuid,
  layer text,
  content text,
  tags text[],
  similarity double precision,
  created_at timestamptz
)
language sql
stable
set search_path = public, extensions
as $$
  select m.id, m.layer, m.content, m.tags,
         (1 - (m.embedding <=> p_embedding))::double precision as similarity,
         m.created_at
  from memory m
  where m.embedding is not null
    and m.status = 'active'
    and (p_layer is null or m.layer = p_layer)
    and (p_exclude is null or m.id <> p_exclude)
  order by m.embedding <=> p_embedding
  limit greatest(p_limit, 1)
$$;

-- Reinforcement write: recall marks what it returned. Returns rows touched.
create or replace function public.memory_mark_referenced(p_ids uuid[])
returns integer
language sql
volatile
set search_path = public, extensions
as $$
  with bumped as (
    update memory
    set last_referenced = now(),
        reference_count = coalesce(reference_count, 0) + 1
    where id = any(p_ids)
    returning 1
  )
  select coalesce(count(*), 0)::integer from bumped
$$;
